sudo: false
dist: trusty
language: java

before_install:
  - pip install --user codecov

jdk:
  - openjdk8
  - openjdk11
  - openjdk14
  - openjdk-ea

arch:
  - amd64
  - ppc64le

matrix:
  allow_failures:
    - jdk: openjdk-ea

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov
